# Generated by Django 2.2.7 on 2019-12-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='create',
        ),
    ]
